### ISSUE TITLE
"Failed to generate download link"

### ISSUE THREAD

**Issue by MuhsinunC** [boy0001/plotupload#3]
Title says it all. It keeps saying "Failed to generate download link" every time I use my own hosted web interface but it works perfectly with the default empcraft one. Please help!

**Comment by MuhsinunC** [comment]
@boy0001

**Comment by boy0001** [comment]
Is it still an issue?

**Comment by MuhsinunC** [comment]
Yep D:
![image](https://cloud.githubusercontent.com/assets/11369216/21960475/432336d0-dabb-11e6-9b1c-0220575fcefa.png)

Vs. Using Empcraft:
![image](https://cloud.githubusercontent.com/assets/11369216/21960479/84ded44e-dabb-11e6-94a9-93b4404a294d.png)

**Comment by MuhsinunC** [comment]
Perhaps these findings may be of use?
These r from my custom version:
![image](https://cloud.githubusercontent.com/assets/11369216/21960490/f0e8953a-dabb-11e6-9ee5-fa2e68a84197.png)

![image](https://cloud.githubusercontent.com/assets/11369216/21960491/fa7618de-dabb-11e6-9f8b-28372119e179.png)

**Comment by boy0001** [comment]
Yeah, so on that it's hardcoded to half a megabyte, which is probably too small. The one I'm hosting, and the latest version have it configurable and it's set to 15MB.

**Comment by MuhsinunC** [comment]
Here's ur version's results:
![image](https://cloud.githubusercontent.com/assets/11369216/21966101/2fd93a72-db3b-11e6-9677-4422905d1103.png)
![image](https://cloud.githubusercontent.com/assets/11369216/21966104/33a1fff4-db3b-11e6-8e21-f93720f27bff.png)

It's still hardcoded in the save file

**Comment by MuhsinunC** [comment]
Even changing this didn't work:
From this:
![image](https://cloud.githubusercontent.com/assets/11369216/21966172/70d7bebc-db3c-11e6-875b-86c8d0d7fbf0.png)

To this:
![image](https://cloud.githubusercontent.com/assets/11369216/21966174/78d18b02-db3c-11e6-9036-1ba99744a656.png)

Issue persists:
![image](https://cloud.githubusercontent.com/assets/11369216/21966177/875e0902-db3c-11e6-98f6-ec83259a13f5.png)

EDIT: Even changing the file size limit in config.php with my change to the save.php file didn't work. I changed it from 15000000 (15 MB) to 50000000 (50 MB)

**Comment by MuhsinunC** [comment]
Did you ever fix it?
